### ISSUE TITLE
How to retrieve `device_token` from inside the device

### ISSUE THREAD

**Issue by nucflash** [eykamp/birdhouse#1]
Hi, thanks for making your work open source, it's very helpful. I'm also working on a solution built on ThingsBoard and I need to deploy a large number of devices. I'm looking for an efficient way to automate this, and your logic in `provision.py` is close to what I've also came up with.

I have one question, in `provision.py#L71`,
https://github.com/eykamp/birdhouse/blob/39ad1541211f911bb7901275d9b596b69f82c61f/management/provision.py#L71
you mention that you store the `device_token` as server attribute so that you can later retrieve it from within the device (or at least this is my wishful interpretation). However, in `fake-sensor.py` it reads a `device_token` from a config file. I'd expect code that does the handshake with ThingsBoard and then queries for the `device_id`. Your comments are helpful!

**Comment by eykamp** [comment]
Hi.  What you are seeing is still very much a work in progress.  fake-sensor.py was one of the first things I wrote on this project, and I haven't revisited it for months.  It's architecture is very much a quick-and-dirty attempt to see if the computer on which I first ran thingsboard could handle multiple devices (it couldn't).  I will likely remove it from the project altogether in the future.

I store the device_id on the server so that when I am post-processing incoming telemetry (using the redlight-greenlight code, which is similarly quick-and-dirty) I can generate new telemetry values to add to the device.  This is how I get the results of the Google wifi geolocation process into the database.  Each device is given its own token during the initial setup (the code for which is not yet in the repo, but will be in a couple of days).  The token_id is stored as a server attribute meaning that  the device cannot access it remotely.

**Comment by nucflash** [comment]
Thanks @eykamp, this is useful. So if I understand correctly, `redlight-greenlight` is your "central" server where all devices send their telemetry data to, and then your server propagates some of the data (after post-processing) to ThingsBoards. 

Can you describe how you get the ThingsBoards device access token into the device? I understand that provision generates a device at ThingsBoard and is aware of the `device_id` and of the `device_token`. And I see that your server, `redlight-greenlight` get the `device_token` from the device to propagate telemetry data to ThingsBoard. What I miss is how you put the `device_token` from `provision` into the device---which is the code that you said it's missing from the repo. I'm looking forward to your ideas!

**Comment by nucflash** [comment]
This is what I ended up doing: 

- register a device on ThingsBoard using REST
- pull the device credentials 
- update the ACCESS_TOKEN with the physical device_id (e.g., manufacturing serial number) plus a salt that is known to both to device and the provisioning script

This way I can independently push devices to ThingsBoard from a provisioning script, and have the device connect to server to pull/send data without burning a ACCESS_TOKEN in it.
